/*
 * Copyright (c) 2023 Yookue Ltd. All rights reserved.
 *
 * Licensed under the MIT License (the "License")
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 */


import React from 'react';
import * as icons from '@ant-design/icons';
import {ReadonlyMultiKeyMap} from '@yookue/ts-multi-map';


export type SceneType = 'direction' | 'suggestion' | 'editor' | 'data' | 'logo' | 'web';


export const outlinedDirectionIcons: ReadonlyMap<string, React.ComponentType<any>> = new Map<string, React.ComponentType<any>>([
    ['StepBackwardOutlined', icons.StepBackwardOutlined],
    ['StepForwardOutlined', icons.StepForwardOutlined],
    ['FastBackwardOutlined', icons.FastBackwardOutlined],
    ['FastForwardOutlined', icons.FastForwardOutlined],
    ['ShrinkOutlined', icons.ShrinkOutlined],
    ['ArrowsAltOutlined', icons.ArrowsAltOutlined],
    ['DownOutlined', icons.DownOutlined],
    ['UpOutlined', icons.UpOutlined],
    ['LeftOutlined', icons.LeftOutlined],
    ['RightOutlined', icons.RightOutlined],
    ['CaretUpOutlined', icons.CaretUpOutlined],
    ['CaretDownOutlined', icons.CaretDownOutlined],
    ['CaretLeftOutlined', icons.CaretLeftOutlined],
    ['CaretRightOutlined', icons.CaretRightOutlined],
    ['UpCircleOutlined', icons.UpCircleOutlined],
    ['DownCircleOutlined', icons.DownCircleOutlined],
    ['LeftCircleOutlined', icons.LeftCircleOutlined],
    ['RightCircleOutlined', icons.RightCircleOutlined],
    ['DoubleRightOutlined', icons.DoubleRightOutlined],
    ['DoubleLeftOutlined', icons.DoubleLeftOutlined],
    ['VerticalLeftOutlined', icons.VerticalLeftOutlined],
    ['VerticalRightOutlined', icons.VerticalRightOutlined],
    ['VerticalAlignTopOutlined', icons.VerticalAlignTopOutlined],
    ['VerticalAlignMiddleOutlined', icons.VerticalAlignMiddleOutlined],
    ['VerticalAlignBottomOutlined', icons.VerticalAlignBottomOutlined],
    ['ForwardOutlined', icons.ForwardOutlined],
    ['BackwardOutlined', icons.BackwardOutlined],
    ['RollbackOutlined', icons.RollbackOutlined],
    ['EnterOutlined', icons.EnterOutlined],
    ['RetweetOutlined', icons.RetweetOutlined],
    ['SwapOutlined', icons.SwapOutlined],
    ['SwapLeftOutlined', icons.SwapLeftOutlined],
    ['SwapRightOutlined', icons.SwapRightOutlined],
    ['ArrowUpOutlined', icons.ArrowUpOutlined],
    ['ArrowDownOutlined', icons.ArrowDownOutlined],
    ['ArrowLeftOutlined', icons.ArrowLeftOutlined],
    ['ArrowRightOutlined', icons.ArrowRightOutlined],
    ['PlayCircleOutlined', icons.PlayCircleOutlined],
    ['UpSquareOutlined', icons.UpSquareOutlined],
    ['DownSquareOutlined', icons.DownSquareOutlined],
    ['LeftSquareOutlined', icons.LeftSquareOutlined],
    ['RightSquareOutlined', icons.RightSquareOutlined],
    ['LoginOutlined', icons.LoginOutlined],
    ['LogoutOutlined', icons.LogoutOutlined],
    ['MenuFoldOutlined', icons.MenuFoldOutlined],
    ['MenuUnfoldOutlined', icons.MenuUnfoldOutlined],
    ['BorderBottomOutlined', icons.BorderBottomOutlined],
    ['BorderHorizontalOutlined', icons.BorderHorizontalOutlined],
    ['BorderInnerOutlined', icons.BorderInnerOutlined],
    ['BorderOuterOutlined', icons.BorderOuterOutlined],
    ['BorderLeftOutlined', icons.BorderLeftOutlined],
    ['BorderRightOutlined', icons.BorderRightOutlined],
    ['BorderTopOutlined', icons.BorderTopOutlined],
    ['BorderVerticleOutlined', icons.BorderVerticleOutlined],
    ['PicCenterOutlined', icons.PicCenterOutlined],
    ['PicLeftOutlined', icons.PicLeftOutlined],
    ['PicRightOutlined', icons.PicRightOutlined],
    ['RadiusBottomleftOutlined', icons.RadiusBottomleftOutlined],
    ['RadiusBottomrightOutlined', icons.RadiusBottomrightOutlined],
    ['RadiusUpleftOutlined', icons.RadiusUpleftOutlined],
    ['RadiusUprightOutlined', icons.RadiusUprightOutlined],
    ['FullscreenOutlined', icons.FullscreenOutlined],
    ['FullscreenExitOutlined', icons.FullscreenExitOutlined],
]);


export const outlinedSuggestionIcons: ReadonlyMap<string, React.ComponentType<any>> = new Map<string, React.ComponentType<any>>([
    ['QuestionOutlined', icons.QuestionOutlined],
    ['QuestionCircleOutlined', icons.QuestionCircleOutlined],
    ['PlusOutlined', icons.PlusOutlined],
    ['PlusCircleOutlined', icons.PlusCircleOutlined],
    ['PauseOutlined', icons.PauseOutlined],
    ['PauseCircleOutlined', icons.PauseCircleOutlined],
    ['MinusOutlined', icons.MinusOutlined],
    ['MinusCircleOutlined', icons.MinusCircleOutlined],
    ['PlusSquareOutlined', icons.PlusSquareOutlined],
    ['MinusSquareOutlined', icons.MinusSquareOutlined],
    ['InfoOutlined', icons.InfoOutlined],
    ['InfoCircleOutlined', icons.InfoCircleOutlined],
    ['ExclamationOutlined', icons.ExclamationOutlined],
    ['ExclamationCircleOutlined', icons.ExclamationCircleOutlined],
    ['CloseOutlined', icons.CloseOutlined],
    ['CloseCircleOutlined', icons.CloseCircleOutlined],
    ['CloseSquareOutlined', icons.CloseSquareOutlined],
    ['CheckOutlined', icons.CheckOutlined],
    ['CheckCircleOutlined', icons.CheckCircleOutlined],
    ['CheckSquareOutlined', icons.CheckSquareOutlined],
    ['ClockCircleOutlined', icons.ClockCircleOutlined],
    ['WarningOutlined', icons.WarningOutlined],
    ['IssuesCloseOutlined', icons.IssuesCloseOutlined],
    ['StopOutlined', icons.StopOutlined],
]);


export const outlinedEditorIcons: ReadonlyMap<string, React.ComponentType<any>> = new Map<string, React.ComponentType<any>>([
    ['EditOutlined', icons.EditOutlined],
    ['FormOutlined', icons.FormOutlined],
    ['CopyOutlined', icons.CopyOutlined],
    ['ScissorOutlined', icons.ScissorOutlined],
    ['DeleteOutlined', icons.DeleteOutlined],
    ['SnippetsOutlined', icons.SnippetsOutlined],
    ['DiffOutlined', icons.DiffOutlined],
    ['HighlightOutlined', icons.HighlightOutlined],
    ['AlignCenterOutlined', icons.AlignCenterOutlined],
    ['AlignLeftOutlined', icons.AlignLeftOutlined],
    ['AlignRightOutlined', icons.AlignRightOutlined],
    ['BgColorsOutlined', icons.BgColorsOutlined],
    ['BoldOutlined', icons.BoldOutlined],
    ['ItalicOutlined', icons.ItalicOutlined],
    ['UnderlineOutlined', icons.UnderlineOutlined],
    ['StrikethroughOutlined', icons.StrikethroughOutlined],
    ['RedoOutlined', icons.RedoOutlined],
    ['UndoOutlined', icons.UndoOutlined],
    ['ZoomInOutlined', icons.ZoomInOutlined],
    ['ZoomOutOutlined', icons.ZoomOutOutlined],
    ['FontColorsOutlined', icons.FontColorsOutlined],
    ['FontSizeOutlined', icons.FontSizeOutlined],
    ['LineHeightOutlined', icons.LineHeightOutlined],
    ['DashOutlined', icons.DashOutlined],
    ['SmallDashOutlined', icons.SmallDashOutlined],
    ['SortAscendingOutlined', icons.SortAscendingOutlined],
    ['SortDescendingOutlined', icons.SortDescendingOutlined],
    ['DragOutlined', icons.DragOutlined],
    ['OrderedListOutlined', icons.OrderedListOutlined],
    ['UnorderedListOutlined', icons.UnorderedListOutlined],
    ['RadiusSettingOutlined', icons.RadiusSettingOutlined],
    ['ColumnWidthOutlined', icons.ColumnWidthOutlined],
    ['ColumnHeightOutlined', icons.ColumnHeightOutlined],
]);


export const outlinedDataIcons: ReadonlyMap<string, React.ComponentType<any>> = new Map<string, React.ComponentType<any>>([
    ['AreaChartOutlined', icons.AreaChartOutlined],
    ['PieChartOutlined', icons.PieChartOutlined],
    ['BarChartOutlined', icons.BarChartOutlined],
    ['DotChartOutlined', icons.DotChartOutlined],
    ['LineChartOutlined', icons.LineChartOutlined],
    ['RadarChartOutlined', icons.RadarChartOutlined],
    ['HeatMapOutlined', icons.HeatMapOutlined],
    ['FallOutlined', icons.FallOutlined],
    ['RiseOutlined', icons.RiseOutlined],
    ['StockOutlined', icons.StockOutlined],
    ['BoxPlotOutlined', icons.BoxPlotOutlined],
    ['FundOutlined', icons.FundOutlined],
    ['SlidersOutlined', icons.SlidersOutlined],
]);


export const outlinedLogoIcons: ReadonlyMap<string, React.ComponentType<any>> = new Map<string, React.ComponentType<any>>([
    ['AndroidOutlined', icons.AndroidOutlined],
    ['AppleOutlined', icons.AppleOutlined],
    ['WindowsOutlined', icons.WindowsOutlined],
    ['IeOutlined', icons.IeOutlined],
    ['ChromeOutlined', icons.ChromeOutlined],
    ['GithubOutlined', icons.GithubOutlined],
    ['AliwangwangOutlined', icons.AliwangwangOutlined],
    ['DingdingOutlined', icons.DingdingOutlined],
    ['WeiboSquareOutlined', icons.WeiboSquareOutlined],
    ['WeiboCircleOutlined', icons.WeiboCircleOutlined],
    ['TaobaoCircleOutlined', icons.TaobaoCircleOutlined],
    ['Html5Outlined', icons.Html5Outlined],
    ['WeiboOutlined', icons.WeiboOutlined],
    ['TwitterOutlined', icons.TwitterOutlined],
    ['WechatOutlined', icons.WechatOutlined],
    ['YoutubeOutlined', icons.YoutubeOutlined],
    ['AlipayCircleOutlined', icons.AlipayCircleOutlined],
    ['TaobaoOutlined', icons.TaobaoOutlined],
    ['SkypeOutlined', icons.SkypeOutlined],
    ['QqOutlined', icons.QqOutlined],
    ['MediumWorkmarkOutlined', icons.MediumWorkmarkOutlined],
    ['GitlabOutlined', icons.GitlabOutlined],
    ['MediumOutlined', icons.MediumOutlined],
    ['LinkedinOutlined', icons.LinkedinOutlined],
    ['GooglePlusOutlined', icons.GooglePlusOutlined],
    ['DropboxOutlined', icons.DropboxOutlined],
    ['FacebookOutlined', icons.FacebookOutlined],
    ['CodepenOutlined', icons.CodepenOutlined],
    ['CodeSandboxOutlined', icons.CodeSandboxOutlined],
    ['AmazonOutlined', icons.AmazonOutlined],
    ['GoogleOutlined', icons.GoogleOutlined],
    ['CodepenCircleOutlined', icons.CodepenCircleOutlined],
    ['AlipayOutlined', icons.AlipayOutlined],
    ['AntDesignOutlined', icons.AntDesignOutlined],
    ['AntCloudOutlined', icons.AntCloudOutlined],
    ['AliyunOutlined', icons.AliyunOutlined],
    ['ZhihuOutlined', icons.ZhihuOutlined],
    ['SlackOutlined', icons.SlackOutlined],
    ['SlackSquareOutlined', icons.SlackSquareOutlined],
    ['BehanceOutlined', icons.BehanceOutlined],
    ['BehanceSquareOutlined', icons.BehanceSquareOutlined],
    ['DribbbleOutlined', icons.DribbbleOutlined],
    ['DribbbleSquareOutlined', icons.DribbbleSquareOutlined],
    ['InstagramOutlined', icons.InstagramOutlined],
    ['YuqueOutlined', icons.YuqueOutlined],
    ['AlibabaOutlined', icons.AlibabaOutlined],
    ['YahooOutlined', icons.YahooOutlined],
    ['RedditOutlined', icons.RedditOutlined],
    ['SketchOutlined', icons.SketchOutlined],
    ['WhatsAppOutlined', icons.WhatsAppOutlined],
    ['DingtalkOutlined', icons.DingtalkOutlined],
]);


export const outlinedWebIcons: ReadonlyMap<string, React.ComponentType<any>> = new Map<string, React.ComponentType<any>>([
    ['AccountBookOutlined', icons.AccountBookOutlined],
    ['AimOutlined', icons.AimOutlined],
    ['AlertOutlined', icons.AlertOutlined],
    ['ApartmentOutlined', icons.ApartmentOutlined],
    ['ApiOutlined', icons.ApiOutlined],
    ['AppstoreAddOutlined', icons.AppstoreAddOutlined],
    ['AppstoreOutlined', icons.AppstoreOutlined],
    ['AudioOutlined', icons.AudioOutlined],
    ['AudioMutedOutlined', icons.AudioMutedOutlined],
    ['AuditOutlined', icons.AuditOutlined],
    ['BankOutlined', icons.BankOutlined],
    ['BarcodeOutlined', icons.BarcodeOutlined],
    ['BarsOutlined', icons.BarsOutlined],
    ['BellOutlined', icons.BellOutlined],
    ['BlockOutlined', icons.BlockOutlined],
    ['BookOutlined', icons.BookOutlined],
    ['BorderOutlined', icons.BorderOutlined],
    ['BorderlessTableOutlined', icons.BorderlessTableOutlined],
    ['BranchesOutlined', icons.BranchesOutlined],
    ['BugOutlined', icons.BugOutlined],
    ['BuildOutlined', icons.BuildOutlined],
    ['BulbOutlined', icons.BulbOutlined],
    ['CalculatorOutlined', icons.CalculatorOutlined],
    ['CalendarOutlined', icons.CalendarOutlined],
    ['CameraOutlined', icons.CameraOutlined],
    ['CarOutlined', icons.CarOutlined],
    ['CarryOutOutlined', icons.CarryOutOutlined],
    ['CiCircleOutlined', icons.CiCircleOutlined],
    ['CiOutlined', icons.CiOutlined],
    ['ClearOutlined', icons.ClearOutlined],
    ['CloudDownloadOutlined', icons.CloudDownloadOutlined],
    ['CloudOutlined', icons.CloudOutlined],
    ['CloudServerOutlined', icons.CloudServerOutlined],
    ['CloudSyncOutlined', icons.CloudSyncOutlined],
    ['CloudUploadOutlined', icons.CloudUploadOutlined],
    ['ClusterOutlined', icons.ClusterOutlined],
    ['CodeOutlined', icons.CodeOutlined],
    ['CoffeeOutlined', icons.CoffeeOutlined],
    ['CommentOutlined', icons.CommentOutlined],
    ['CompassOutlined', icons.CompassOutlined],
    ['CompressOutlined', icons.CompressOutlined],
    ['ConsoleSqlOutlined', icons.ConsoleSqlOutlined],
    ['ContactsOutlined', icons.ContactsOutlined],
    ['ContainerOutlined', icons.ContainerOutlined],
    ['ControlOutlined', icons.ControlOutlined],
    ['CopyrightOutlined', icons.CopyrightOutlined],
    ['CreditCardOutlined', icons.CreditCardOutlined],
    ['CrownOutlined', icons.CrownOutlined],
    ['CustomerServiceOutlined', icons.CustomerServiceOutlined],
    ['DashboardOutlined', icons.DashboardOutlined],
    ['DatabaseOutlined', icons.DatabaseOutlined],
    ['DeleteColumnOutlined', icons.DeleteColumnOutlined],
    ['DeleteRowOutlined', icons.DeleteRowOutlined],
    ['DeliveredProcedureOutlined', icons.DeliveredProcedureOutlined],
    ['DeploymentUnitOutlined', icons.DeploymentUnitOutlined],
    ['DesktopOutlined', icons.DesktopOutlined],
    ['DisconnectOutlined', icons.DisconnectOutlined],
    ['DislikeOutlined', icons.DislikeOutlined],
    ['DollarCircleOutlined', icons.DollarCircleOutlined],
    ['DollarOutlined', icons.DollarOutlined],
    ['DownloadOutlined', icons.DownloadOutlined],
    ['EllipsisOutlined', icons.EllipsisOutlined],
    ['EnvironmentOutlined', icons.EnvironmentOutlined],
    ['EuroCircleOutlined', icons.EuroCircleOutlined],
    ['EuroOutlined', icons.EuroOutlined],
    ['ExceptionOutlined', icons.ExceptionOutlined],
    ['ExpandAltOutlined', icons.ExpandAltOutlined],
    ['ExpandOutlined', icons.ExpandOutlined],
    ['ExperimentOutlined', icons.ExperimentOutlined],
    ['ExportOutlined', icons.ExportOutlined],
    ['EyeOutlined', icons.EyeOutlined],
    ['EyeInvisibleOutlined', icons.EyeInvisibleOutlined],
    ['FieldBinaryOutlined', icons.FieldBinaryOutlined],
    ['FieldNumberOutlined', icons.FieldNumberOutlined],
    ['FieldStringOutlined', icons.FieldStringOutlined],
    ['FieldTimeOutlined', icons.FieldTimeOutlined],
    ['FileAddOutlined', icons.FileAddOutlined],
    ['FileDoneOutlined', icons.FileDoneOutlined],
    ['FileExcelOutlined', icons.FileExcelOutlined],
    ['FileExclamationOutlined', icons.FileExclamationOutlined],
    ['FileOutlined', icons.FileOutlined],
    ['FileGifOutlined', icons.FileGifOutlined],
    ['FileImageOutlined', icons.FileImageOutlined],
    ['FileJpgOutlined', icons.FileJpgOutlined],
    ['FileMarkdownOutlined', icons.FileMarkdownOutlined],
    ['FilePdfOutlined', icons.FilePdfOutlined],
    ['FilePptOutlined', icons.FilePptOutlined],
    ['FileProtectOutlined', icons.FileProtectOutlined],
    ['FileSearchOutlined', icons.FileSearchOutlined],
    ['FileSyncOutlined', icons.FileSyncOutlined],
    ['FileTextOutlined', icons.FileTextOutlined],
    ['FileUnknownOutlined', icons.FileUnknownOutlined],
    ['FileWordOutlined', icons.FileWordOutlined],
    ['FileZipOutlined', icons.FileZipOutlined],
    ['FilterOutlined', icons.FilterOutlined],
    ['FireOutlined', icons.FireOutlined],
    ['FlagOutlined', icons.FlagOutlined],
    ['FolderAddOutlined', icons.FolderAddOutlined],
    ['FolderOutlined', icons.FolderOutlined],
    ['FolderOpenOutlined', icons.FolderOpenOutlined],
    ['FolderViewOutlined', icons.FolderViewOutlined],
    ['ForkOutlined', icons.ForkOutlined],
    ['FormatPainterOutlined', icons.FormatPainterOutlined],
    ['FrownOutlined', icons.FrownOutlined],
    ['FunctionOutlined', icons.FunctionOutlined],
    ['FundProjectionScreenOutlined', icons.FundProjectionScreenOutlined],
    ['FundViewOutlined', icons.FundViewOutlined],
    ['FunnelPlotOutlined', icons.FunnelPlotOutlined],
    ['GatewayOutlined', icons.GatewayOutlined],
    ['GifOutlined', icons.GifOutlined],
    ['GiftOutlined', icons.GiftOutlined],
    ['GlobalOutlined', icons.GlobalOutlined],
    ['GoldOutlined', icons.GoldOutlined],
    ['GroupOutlined', icons.GroupOutlined],
    ['HddOutlined', icons.HddOutlined],
    ['HeartOutlined', icons.HeartOutlined],
    ['HistoryOutlined', icons.HistoryOutlined],
    ['HolderOutlined', icons.HolderOutlined],
    ['HomeOutlined', icons.HomeOutlined],
    ['HourglassOutlined', icons.HourglassOutlined],
    ['IdcardOutlined', icons.IdcardOutlined],
    ['ImportOutlined', icons.ImportOutlined],
    ['InboxOutlined', icons.InboxOutlined],
    ['InsertRowAboveOutlined', icons.InsertRowAboveOutlined],
    ['InsertRowBelowOutlined', icons.InsertRowBelowOutlined],
    ['InsertRowLeftOutlined', icons.InsertRowLeftOutlined],
    ['InsertRowRightOutlined', icons.InsertRowRightOutlined],
    ['InsuranceOutlined', icons.InsuranceOutlined],
    ['InteractionOutlined', icons.InteractionOutlined],
    ['KeyOutlined', icons.KeyOutlined],
    ['LaptopOutlined', icons.LaptopOutlined],
    ['LayoutOutlined', icons.LayoutOutlined],
    ['LikeOutlined', icons.LikeOutlined],
    ['LineOutlined', icons.LineOutlined],
    ['LinkOutlined', icons.LinkOutlined],
    ['Loading3QuartersOutlined', icons.Loading3QuartersOutlined],
    ['LoadingOutlined', icons.LoadingOutlined],
    ['LockOutlined', icons.LockOutlined],
    ['MacCommandOutlined', icons.MacCommandOutlined],
    ['MailOutlined', icons.MailOutlined],
    ['ManOutlined', icons.ManOutlined],
    ['MedicineBoxOutlined', icons.MedicineBoxOutlined],
    ['MehOutlined', icons.MehOutlined],
    ['MenuOutlined', icons.MenuOutlined],
    ['MergeCellsOutlined', icons.MergeCellsOutlined],
    ['MessageOutlined', icons.MessageOutlined],
    ['MobileOutlined', icons.MobileOutlined],
    ['MoneyCollectOutlined', icons.MoneyCollectOutlined],
    ['MonitorOutlined', icons.MonitorOutlined],
    ['MoreOutlined', icons.MoreOutlined],
    ['NodeCollapseOutlined', icons.NodeCollapseOutlined],
    ['NodeExpandOutlined', icons.NodeExpandOutlined],
    ['NodeIndexOutlined', icons.NodeIndexOutlined],
    ['NotificationOutlined', icons.NotificationOutlined],
    ['NumberOutlined', icons.NumberOutlined],
    ['OneToOneOutlined', icons.OneToOneOutlined],
    ['PaperClipOutlined', icons.PaperClipOutlined],
    ['PartitionOutlined', icons.PartitionOutlined],
    ['PayCircleOutlined', icons.PayCircleOutlined],
    ['PercentageOutlined', icons.PercentageOutlined],
    ['PhoneOutlined', icons.PhoneOutlined],
    ['PictureOutlined', icons.PictureOutlined],
    ['PlaySquareOutlined', icons.PlaySquareOutlined],
    ['PoundCircleOutlined', icons.PoundCircleOutlined],
    ['PoundOutlined', icons.PoundOutlined],
    ['PoweroffOutlined', icons.PoweroffOutlined],
    ['PrinterOutlined', icons.PrinterOutlined],
    ['ProfileOutlined', icons.ProfileOutlined],
    ['ProjectOutlined', icons.ProjectOutlined],
    ['PropertySafetyOutlined', icons.PropertySafetyOutlined],
    ['PullRequestOutlined', icons.PullRequestOutlined],
    ['PushpinOutlined', icons.PushpinOutlined],
    ['QrcodeOutlined', icons.QrcodeOutlined],
    ['ReadOutlined', icons.ReadOutlined],
    ['ReconciliationOutlined', icons.ReconciliationOutlined],
    ['RedEnvelopeOutlined', icons.RedEnvelopeOutlined],
    ['ReloadOutlined', icons.ReloadOutlined],
    ['RestOutlined', icons.RestOutlined],
    ['RobotOutlined', icons.RobotOutlined],
    ['RocketOutlined', icons.RocketOutlined],
    ['RotateLeftOutlined', icons.RotateLeftOutlined],
    ['RotateRightOutlined', icons.RotateRightOutlined],
    ['SafetyCertificateOutlined', icons.SafetyCertificateOutlined],
    ['SafetyOutlined', icons.SafetyOutlined],
    ['SaveOutlined', icons.SaveOutlined],
    ['ScanOutlined', icons.ScanOutlined],
    ['ScheduleOutlined', icons.ScheduleOutlined],
    ['SearchOutlined', icons.SearchOutlined],
    ['SecurityScanOutlined', icons.SecurityScanOutlined],
    ['SelectOutlined', icons.SelectOutlined],
    ['SendOutlined', icons.SendOutlined],
    ['SettingOutlined', icons.SettingOutlined],
    ['ShakeOutlined', icons.ShakeOutlined],
    ['ShareAltOutlined', icons.ShareAltOutlined],
    ['ShopOutlined', icons.ShopOutlined],
    ['ShoppingCartOutlined', icons.ShoppingCartOutlined],
    ['ShoppingOutlined', icons.ShoppingOutlined],
    ['SisternodeOutlined', icons.SisternodeOutlined],
    ['SkinOutlined', icons.SkinOutlined],
    ['SmileOutlined', icons.SmileOutlined],
    ['SolutionOutlined', icons.SolutionOutlined],
    ['SoundOutlined', icons.SoundOutlined],
    ['SplitCellsOutlined', icons.SplitCellsOutlined],
    ['StarOutlined', icons.StarOutlined],
    ['SubnodeOutlined', icons.SubnodeOutlined],
    ['SwitcherOutlined', icons.SwitcherOutlined],
    ['SyncOutlined', icons.SyncOutlined],
    ['TableOutlined', icons.TableOutlined],
    ['TabletOutlined', icons.TabletOutlined],
    ['TagOutlined', icons.TagOutlined],
    ['TagsOutlined', icons.TagsOutlined],
    ['TeamOutlined', icons.TeamOutlined],
    ['ThunderboltOutlined', icons.ThunderboltOutlined],
    ['ToTopOutlined', icons.ToTopOutlined],
    ['ToolOutlined', icons.ToolOutlined],
    ['TrademarkCircleOutlined', icons.TrademarkCircleOutlined],
    ['TrademarkOutlined', icons.TrademarkOutlined],
    ['TransactionOutlined', icons.TransactionOutlined],
    ['TranslationOutlined', icons.TranslationOutlined],
    ['TrophyOutlined', icons.TrophyOutlined],
    ['UngroupOutlined', icons.UngroupOutlined],
    ['UnlockOutlined', icons.UnlockOutlined],
    ['UploadOutlined', icons.UploadOutlined],
    ['UsbOutlined', icons.UsbOutlined],
    ['UserAddOutlined', icons.UserAddOutlined],
    ['UserDeleteOutlined', icons.UserDeleteOutlined],
    ['UserOutlined', icons.UserOutlined],
    ['UserSwitchOutlined', icons.UserSwitchOutlined],
    ['UsergroupAddOutlined', icons.UsergroupAddOutlined],
    ['UsergroupDeleteOutlined', icons.UsergroupDeleteOutlined],
    ['VerifiedOutlined', icons.VerifiedOutlined],
    ['VideoCameraAddOutlined', icons.VideoCameraAddOutlined],
    ['VideoCameraOutlined', icons.VideoCameraOutlined],
    ['WalletOutlined', icons.WalletOutlined],
    ['WifiOutlined', icons.WifiOutlined],
    ['WomanOutlined', icons.WomanOutlined],
]);


export const filledDirectionIcons: ReadonlyMap<string, React.ComponentType<any>> = new Map<string, React.ComponentType<any>>([
    ['StepBackwardFilled', icons.StepBackwardFilled],
    ['StepForwardFilled', icons.StepForwardFilled],
    ['FastBackwardFilled', icons.FastBackwardFilled],
    ['FastForwardFilled', icons.FastForwardFilled],
    ['CaretUpFilled', icons.CaretUpFilled],
    ['CaretDownFilled', icons.CaretDownFilled],
    ['CaretLeftFilled', icons.CaretLeftFilled],
    ['CaretRightFilled', icons.CaretRightFilled],
    ['UpCircleFilled', icons.UpCircleFilled],
    ['DownCircleFilled', icons.DownCircleFilled],
    ['LeftCircleFilled', icons.LeftCircleFilled],
    ['RightCircleFilled', icons.RightCircleFilled],
    ['ForwardFilled', icons.ForwardFilled],
    ['BackwardFilled', icons.BackwardFilled],
    ['PlayCircleFilled', icons.PlayCircleFilled],
    ['UpSquareFilled', icons.UpSquareFilled],
    ['DownSquareFilled', icons.DownSquareFilled],
    ['LeftSquareFilled', icons.LeftSquareFilled],
    ['RightSquareFilled', icons.RightSquareFilled],
]);


export const filledSuggestionIcons: ReadonlyMap<string, React.ComponentType<any>> = new Map<string, React.ComponentType<any>>([
    ['QuestionCircleFilled', icons.QuestionCircleFilled],
    ['PlusCircleFilled', icons.PlusCircleFilled],
    ['PauseCircleFilled', icons.PauseCircleFilled],
    ['MinusCircleFilled', icons.MinusCircleFilled],
    ['PlusSquareFilled', icons.PlusSquareFilled],
    ['MinusSquareFilled', icons.MinusSquareFilled],
    ['InfoCircleFilled', icons.InfoCircleFilled],
    ['ExclamationCircleFilled', icons.ExclamationCircleFilled],
    ['CloseCircleFilled', icons.CloseCircleFilled],
    ['CloseSquareFilled', icons.CloseSquareFilled],
    ['CheckCircleFilled', icons.CheckCircleFilled],
    ['CheckSquareFilled', icons.CheckSquareFilled],
    ['ClockCircleFilled', icons.ClockCircleFilled],
    ['WarningFilled', icons.WarningFilled],
    ['StopFilled', icons.StopFilled],
]);


export const filledEditorIcons: ReadonlyMap<string, React.ComponentType<any>> = new Map<string, React.ComponentType<any>>([
    ['EditFilled', icons.EditFilled],
    ['CopyFilled', icons.CopyFilled],
    ['DeleteFilled', icons.DeleteFilled],
    ['SnippetsFilled', icons.SnippetsFilled],
    ['DiffFilled', icons.DiffFilled],
    ['HighlightFilled', icons.HighlightFilled],
]);


export const filledDataIcons: ReadonlyMap<string, React.ComponentType<any>> = new Map<string, React.ComponentType<any>>([
    ['PieChartFilled', icons.PieChartFilled],
    ['BoxPlotFilled', icons.BoxPlotFilled],
    ['FundFilled', icons.FundFilled],
    ['SlidersFilled', icons.SlidersFilled],
]);


export const filledLogoIcons: ReadonlyMap<string, React.ComponentType<any>> = new Map<string, React.ComponentType<any>>([
    ['AndroidFilled', icons.AndroidFilled],
    ['AppleFilled', icons.AppleFilled],
    ['WindowsFilled', icons.WindowsFilled],
    ['ChromeFilled', icons.ChromeFilled],
    ['GithubFilled', icons.GithubFilled],
    ['AliwangwangFilled', icons.AliwangwangFilled],
    ['WeiboSquareFilled', icons.WeiboSquareFilled],
    ['WeiboCircleFilled', icons.WeiboCircleFilled],
    ['TaobaoCircleFilled', icons.TaobaoCircleFilled],
    ['Html5Filled', icons.Html5Filled],
    ['WechatFilled', icons.WechatFilled],
    ['YoutubeFilled', icons.YoutubeFilled],
    ['AlipayCircleFilled', icons.AlipayCircleFilled],
    ['SkypeFilled', icons.SkypeFilled],
    ['GitlabFilled', icons.GitlabFilled],
    ['LinkedinFilled', icons.LinkedinFilled],
    ['FacebookFilled', icons.FacebookFilled],
    ['CodeSandboxCircleFilled', icons.CodeSandboxCircleFilled],
    ['CodepenCircleFilled', icons.CodepenCircleFilled],
    ['SlackSquareFilled', icons.SlackSquareFilled],
    ['BehanceSquareFilled', icons.BehanceSquareFilled],
    ['DribbbleSquareFilled', icons.DribbbleSquareFilled],
    ['InstagramFilled', icons.InstagramFilled],
    ['YuqueFilled', icons.YuqueFilled],
    ['YahooFilled', icons.YahooFilled],
]);


export const filledWebIcons: ReadonlyMap<string, React.ComponentType<any>> = new Map<string, React.ComponentType<any>>([
    ['AccountBookFilled', icons.AccountBookFilled],
    ['AlertFilled', icons.AlertFilled],
    ['AlipaySquareFilled', icons.AlipaySquareFilled],
    ['AmazonCircleFilled', icons.AmazonCircleFilled],
    ['AmazonSquareFilled', icons.AmazonSquareFilled],
    ['ApiFilled', icons.ApiFilled],
    ['AppstoreFilled', icons.AppstoreFilled],
    ['AudioFilled', icons.AudioFilled],
    ['BankFilled', icons.BankFilled],
    ['BehanceCircleFilled', icons.BehanceCircleFilled],
    ['BellFilled', icons.BellFilled],
    ['BookFilled', icons.BookFilled],
    ['BugFilled', icons.BugFilled],
    ['BuildFilled', icons.BuildFilled],
    ['BulbFilled', icons.BulbFilled],
    ['CalculatorFilled', icons.CalculatorFilled],
    ['CalendarFilled', icons.CalendarFilled],
    ['CameraFilled', icons.CameraFilled],
    ['CarFilled', icons.CarFilled],
    ['CarryOutFilled', icons.CarryOutFilled],
    ['CiCircleFilled', icons.CiCircleFilled],
    ['CloudFilled', icons.CloudFilled],
    ['CodeFilled', icons.CodeFilled],
    ['CodeSandboxSquareFilled', icons.CodeSandboxSquareFilled],
    ['CodepenSquareFilled', icons.CodepenSquareFilled],
    ['CompassFilled', icons.CompassFilled],
    ['ContactsFilled', icons.ContactsFilled],
    ['ContainerFilled', icons.ContainerFilled],
    ['ControlFilled', icons.ControlFilled],
    ['CreditCardFilled', icons.CreditCardFilled],
    ['CrownFilled', icons.CrownFilled],
    ['CustomerServiceFilled', icons.CustomerServiceFilled],
    ['DashboardFilled', icons.DashboardFilled],
    ['DatabaseFilled', icons.DatabaseFilled],
    ['DingtalkCircleFilled', icons.DingtalkCircleFilled],
    ['DingtalkSquareFilled', icons.DingtalkSquareFilled],
    ['DislikeFilled', icons.DislikeFilled],
    ['DollarCircleFilled', icons.DollarCircleFilled],
    ['DribbbleCircleFilled', icons.DribbbleCircleFilled],
    ['DropboxCircleFilled', icons.DropboxCircleFilled],
    ['DropboxSquareFilled', icons.DropboxSquareFilled],
    ['EnvironmentFilled', icons.EnvironmentFilled],
    ['EuroCircleFilled', icons.EuroCircleFilled],
    ['ExperimentFilled', icons.ExperimentFilled],
    ['EyeFilled', icons.EyeFilled],
    ['EyeInvisibleFilled', icons.EyeInvisibleFilled],
    ['FileAddFilled', icons.FileAddFilled],
    ['FileExcelFilled', icons.FileExcelFilled],
    ['FileExclamationFilled', icons.FileExclamationFilled],
    ['FileFilled', icons.FileFilled],
    ['FileImageFilled', icons.FileImageFilled],
    ['FileMarkdownFilled', icons.FileMarkdownFilled],
    ['FilePdfFilled', icons.FilePdfFilled],
    ['FilePptFilled', icons.FilePptFilled],
    ['FileTextFilled', icons.FileTextFilled],
    ['FileUnknownFilled', icons.FileUnknownFilled],
    ['FileWordFilled', icons.FileWordFilled],
    ['FileZipFilled', icons.FileZipFilled],
    ['FilterFilled', icons.FilterFilled],
    ['FireFilled', icons.FireFilled],
    ['FlagFilled', icons.FlagFilled],
    ['FolderAddFilled', icons.FolderAddFilled],
    ['FolderFilled', icons.FolderFilled],
    ['FolderOpenFilled', icons.FolderOpenFilled],
    ['FormatPainterFilled', icons.FormatPainterFilled],
    ['FrownFilled', icons.FrownFilled],
    ['FunnelPlotFilled', icons.FunnelPlotFilled],
    ['GiftFilled', icons.GiftFilled],
    ['GoldFilled', icons.GoldFilled],
    ['GoldenFilled', icons.GoldenFilled],
    ['GoogleCircleFilled', icons.GoogleCircleFilled],
    ['GooglePlusCircleFilled', icons.GooglePlusCircleFilled],
    ['GooglePlusSquareFilled', icons.GooglePlusSquareFilled],
    ['GoogleSquareFilled', icons.GoogleSquareFilled],
    ['HddFilled', icons.HddFilled],
    ['HeartFilled', icons.HeartFilled],
    ['HomeFilled', icons.HomeFilled],
    ['HourglassFilled', icons.HourglassFilled],
    ['IdcardFilled', icons.IdcardFilled],
    ['IeCircleFilled', icons.IeCircleFilled],
    ['IeSquareFilled', icons.IeSquareFilled],
    ['InsuranceFilled', icons.InsuranceFilled],
    ['InteractionFilled', icons.InteractionFilled],
    ['LayoutFilled', icons.LayoutFilled],
    ['LikeFilled', icons.LikeFilled],
    ['LockFilled', icons.LockFilled],
    ['MacCommandFilled', icons.MacCommandFilled],
    ['MailFilled', icons.MailFilled],
    ['MedicineBoxFilled', icons.MedicineBoxFilled],
    ['MediumCircleFilled', icons.MediumCircleFilled],
    ['MediumSquareFilled', icons.MediumSquareFilled],
    ['MehFilled', icons.MehFilled],
    ['MessageFilled', icons.MessageFilled],
    ['MobileFilled', icons.MobileFilled],
    ['MoneyCollectFilled', icons.MoneyCollectFilled],
    ['NotificationFilled', icons.NotificationFilled],
    ['PayCircleFilled', icons.PayCircleFilled],
    ['PhoneFilled', icons.PhoneFilled],
    ['PictureFilled', icons.PictureFilled],
    ['PlaySquareFilled', icons.PlaySquareFilled],
    ['PoundCircleFilled', icons.PoundCircleFilled],
    ['PrinterFilled', icons.PrinterFilled],
    ['ProfileFilled', icons.ProfileFilled],
    ['ProjectFilled', icons.ProjectFilled],
    ['PropertySafetyFilled', icons.PropertySafetyFilled],
    ['PushpinFilled', icons.PushpinFilled],
    ['QqCircleFilled', icons.QqCircleFilled],
    ['QqSquareFilled', icons.QqSquareFilled],
    ['ReadFilled', icons.ReadFilled],
    ['ReconciliationFilled', icons.ReconciliationFilled],
    ['RedEnvelopeFilled', icons.RedEnvelopeFilled],
    ['RedditCircleFilled', icons.RedditCircleFilled],
    ['RedditSquareFilled', icons.RedditSquareFilled],
    ['RestFilled', icons.RestFilled],
    ['RobotFilled', icons.RobotFilled],
    ['RocketFilled', icons.RocketFilled],
    ['SafetyCertificateFilled', icons.SafetyCertificateFilled],
    ['SaveFilled', icons.SaveFilled],
    ['ScheduleFilled', icons.ScheduleFilled],
    ['SecurityScanFilled', icons.SecurityScanFilled],
    ['SettingFilled', icons.SettingFilled],
    ['ShopFilled', icons.ShopFilled],
    ['ShoppingFilled', icons.ShoppingFilled],
    ['SignalFilled', icons.SignalFilled],
    ['SketchCircleFilled', icons.SketchCircleFilled],
    ['SketchSquareFilled', icons.SketchSquareFilled],
    ['SkinFilled', icons.SkinFilled],
    ['SlackCircleFilled', icons.SlackCircleFilled],
    ['SmileFilled', icons.SmileFilled],
    ['SoundFilled', icons.SoundFilled],
    ['StarFilled', icons.StarFilled],
    ['SwitcherFilled', icons.SwitcherFilled],
    ['TabletFilled', icons.TabletFilled],
    ['TagFilled', icons.TagFilled],
    ['TagsFilled', icons.TagsFilled],
    ['TaobaoSquareFilled', icons.TaobaoSquareFilled],
    ['ThunderboltFilled', icons.ThunderboltFilled],
    ['ToolFilled', icons.ToolFilled],
    ['TrademarkCircleFilled', icons.TrademarkCircleFilled],
    ['TrophyFilled', icons.TrophyFilled],
    ['TwitterCircleFilled', icons.TwitterCircleFilled],
    ['TwitterSquareFilled', icons.TwitterSquareFilled],
    ['UnlockFilled', icons.UnlockFilled],
    ['UsbFilled', icons.UsbFilled],
    ['VideoCameraFilled', icons.VideoCameraFilled],
    ['WalletFilled', icons.WalletFilled],
    ['ZhihuCircleFilled', icons.ZhihuCircleFilled],
    ['ZhihuSquareFilled', icons.ZhihuSquareFilled],
]);


export const twotoneDirectionIcons: ReadonlyMap<string, React.ComponentType<any>> = new Map<string, React.ComponentType<any>>([
    ['UpCircleTwoTone', icons.UpCircleTwoTone],
    ['DownCircleTwoTone', icons.DownCircleTwoTone],
    ['LeftCircleTwoTone', icons.LeftCircleTwoTone],
    ['RightCircleTwoTone', icons.RightCircleTwoTone],
    ['PlayCircleTwoTone', icons.PlayCircleTwoTone],
    ['UpSquareTwoTone', icons.UpSquareTwoTone],
    ['DownSquareTwoTone', icons.DownSquareTwoTone],
    ['LeftSquareTwoTone', icons.LeftSquareTwoTone],
    ['RightSquareTwoTone', icons.RightSquareTwoTone],
]);


export const twotoneSuggestionIcons: ReadonlyMap<string, React.ComponentType<any>> = new Map<string, React.ComponentType<any>>([
    ['QuestionCircleTwoTone', icons.QuestionCircleTwoTone],
    ['PlusCircleTwoTone', icons.PlusCircleTwoTone],
    ['PauseCircleTwoTone', icons.PauseCircleTwoTone],
    ['MinusCircleTwoTone', icons.MinusCircleTwoTone],
    ['PlusSquareTwoTone', icons.PlusSquareTwoTone],
    ['MinusSquareTwoTone', icons.MinusSquareTwoTone],
    ['InfoCircleTwoTone', icons.InfoCircleTwoTone],
    ['ExclamationCircleTwoTone', icons.ExclamationCircleTwoTone],
    ['CloseCircleTwoTone', icons.CloseCircleTwoTone],
    ['CloseSquareTwoTone', icons.CloseSquareTwoTone],
    ['CheckCircleTwoTone', icons.CheckCircleTwoTone],
    ['CheckSquareTwoTone', icons.CheckSquareTwoTone],
    ['ClockCircleTwoTone', icons.ClockCircleTwoTone],
    ['WarningTwoTone', icons.WarningTwoTone],
    ['StopTwoTone', icons.StopTwoTone],
]);


export const twotoneEditorIcons: ReadonlyMap<string, React.ComponentType<any>> = new Map<string, React.ComponentType<any>>([
    ['EditTwoTone', icons.EditTwoTone],
    ['CopyTwoTone', icons.CopyTwoTone],
    ['DeleteTwoTone', icons.DeleteTwoTone],
    ['SnippetsTwoTone', icons.SnippetsTwoTone],
    ['DiffTwoTone', icons.DiffTwoTone],
    ['HighlightTwoTone', icons.HighlightTwoTone],
]);


export const twotoneDataIcons: ReadonlyMap<string, React.ComponentType<any>> = new Map<string, React.ComponentType<any>>([
    ['PieChartTwoTone', icons.PieChartTwoTone],
    ['BoxPlotTwoTone', icons.BoxPlotTwoTone],
    ['FundTwoTone', icons.FundTwoTone],
    ['SlidersTwoTone', icons.SlidersTwoTone],
]);


export const twotoneLogoIcons: ReadonlyMap<string, React.ComponentType<any>> = new Map<string, React.ComponentType<any>>([
    ['Html5TwoTone', icons.Html5TwoTone],
]);


export const twotoneWebIcons: ReadonlyMap<string, React.ComponentType<any>> = new Map<string, React.ComponentType<any>>([
    ['AccountBookTwoTone', icons.AccountBookTwoTone],
    ['AlertTwoTone', icons.AlertTwoTone],
    ['ApiTwoTone', icons.ApiTwoTone],
    ['AppstoreTwoTone', icons.AppstoreTwoTone],
    ['AudioTwoTone', icons.AudioTwoTone],
    ['BankTwoTone', icons.BankTwoTone],
    ['BellTwoTone', icons.BellTwoTone],
    ['BookTwoTone', icons.BookTwoTone],
    ['BugTwoTone', icons.BugTwoTone],
    ['BuildTwoTone', icons.BuildTwoTone],
    ['BulbTwoTone', icons.BulbTwoTone],
    ['CalculatorTwoTone', icons.CalculatorTwoTone],
    ['CalendarTwoTone', icons.CalendarTwoTone],
    ['CameraTwoTone', icons.CameraTwoTone],
    ['CarTwoTone', icons.CarTwoTone],
    ['CarryOutTwoTone', icons.CarryOutTwoTone],
    ['CiCircleTwoTone', icons.CiCircleTwoTone],
    ['CiTwoTone', icons.CiTwoTone],
    ['CloudTwoTone', icons.CloudTwoTone],
    ['CodeTwoTone', icons.CodeTwoTone],
    ['CompassTwoTone', icons.CompassTwoTone],
    ['ContactsTwoTone', icons.ContactsTwoTone],
    ['ContainerTwoTone', icons.ContainerTwoTone],
    ['ControlTwoTone', icons.ControlTwoTone],
    ['CopyrightTwoTone', icons.CopyrightTwoTone],
    ['CreditCardTwoTone', icons.CreditCardTwoTone],
    ['CrownTwoTone', icons.CrownTwoTone],
    ['CustomerServiceTwoTone', icons.CustomerServiceTwoTone],
    ['DashboardTwoTone', icons.DashboardTwoTone],
    ['DatabaseTwoTone', icons.DatabaseTwoTone],
    ['DislikeTwoTone', icons.DislikeTwoTone],
    ['DollarCircleTwoTone', icons.DollarCircleTwoTone],
    ['DollarTwoTone', icons.DollarTwoTone],
    ['EnvironmentTwoTone', icons.EnvironmentTwoTone],
    ['EuroCircleTwoTone', icons.EuroCircleTwoTone],
    ['EuroTwoTone', icons.EuroTwoTone],
    ['ExperimentTwoTone', icons.ExperimentTwoTone],
    ['EyeTwoTone', icons.EyeTwoTone],
    ['EyeInvisibleTwoTone', icons.EyeInvisibleTwoTone],
    ['FileAddTwoTone', icons.FileAddTwoTone],
    ['FileExcelTwoTone', icons.FileExcelTwoTone],
    ['FileExclamationTwoTone', icons.FileExclamationTwoTone],
    ['FileTwoTone', icons.FileTwoTone],
    ['FileImageTwoTone', icons.FileImageTwoTone],
    ['FileMarkdownTwoTone', icons.FileMarkdownTwoTone],
    ['FilePdfTwoTone', icons.FilePdfTwoTone],
    ['FilePptTwoTone', icons.FilePptTwoTone],
    ['FileTextTwoTone', icons.FileTextTwoTone],
    ['FileUnknownTwoTone', icons.FileUnknownTwoTone],
    ['FileWordTwoTone', icons.FileWordTwoTone],
    ['FileZipTwoTone', icons.FileZipTwoTone],
    ['FilterTwoTone', icons.FilterTwoTone],
    ['FireTwoTone', icons.FireTwoTone],
    ['FlagTwoTone', icons.FlagTwoTone],
    ['FolderAddTwoTone', icons.FolderAddTwoTone],
    ['FolderTwoTone', icons.FolderTwoTone],
    ['FolderOpenTwoTone', icons.FolderOpenTwoTone],
    ['FrownTwoTone', icons.FrownTwoTone],
    ['FunnelPlotTwoTone', icons.FunnelPlotTwoTone],
    ['GiftTwoTone', icons.GiftTwoTone],
    ['GoldTwoTone', icons.GoldTwoTone],
    ['HddTwoTone', icons.HddTwoTone],
    ['HeartTwoTone', icons.HeartTwoTone],
    ['HomeTwoTone', icons.HomeTwoTone],
    ['HourglassTwoTone', icons.HourglassTwoTone],
    ['IdcardTwoTone', icons.IdcardTwoTone],
    ['InsuranceTwoTone', icons.InsuranceTwoTone],
    ['InteractionTwoTone', icons.InteractionTwoTone],
    ['LayoutTwoTone', icons.LayoutTwoTone],
    ['LikeTwoTone', icons.LikeTwoTone],
    ['LockTwoTone', icons.LockTwoTone],
    ['MailTwoTone', icons.MailTwoTone],
    ['MedicineBoxTwoTone', icons.MedicineBoxTwoTone],
    ['MehTwoTone', icons.MehTwoTone],
    ['MessageTwoTone', icons.MessageTwoTone],
    ['MobileTwoTone', icons.MobileTwoTone],
    ['MoneyCollectTwoTone', icons.MoneyCollectTwoTone],
    ['NotificationTwoTone', icons.NotificationTwoTone],
    ['PhoneTwoTone', icons.PhoneTwoTone],
    ['PictureTwoTone', icons.PictureTwoTone],
    ['PlaySquareTwoTone', icons.PlaySquareTwoTone],
    ['PoundCircleTwoTone', icons.PoundCircleTwoTone],
    ['PrinterTwoTone', icons.PrinterTwoTone],
    ['ProfileTwoTone', icons.ProfileTwoTone],
    ['ProjectTwoTone', icons.ProjectTwoTone],
    ['PropertySafetyTwoTone', icons.PropertySafetyTwoTone],
    ['PushpinTwoTone', icons.PushpinTwoTone],
    ['ReconciliationTwoTone', icons.ReconciliationTwoTone],
    ['RedEnvelopeTwoTone', icons.RedEnvelopeTwoTone],
    ['RestTwoTone', icons.RestTwoTone],
    ['RocketTwoTone', icons.RocketTwoTone],
    ['SafetyCertificateTwoTone', icons.SafetyCertificateTwoTone],
    ['SaveTwoTone', icons.SaveTwoTone],
    ['ScheduleTwoTone', icons.ScheduleTwoTone],
    ['SecurityScanTwoTone', icons.SecurityScanTwoTone],
    ['SettingTwoTone', icons.SettingTwoTone],
    ['ShopTwoTone', icons.ShopTwoTone],
    ['ShoppingTwoTone', icons.ShoppingTwoTone],
    ['SkinTwoTone', icons.SkinTwoTone],
    ['SmileTwoTone', icons.SmileTwoTone],
    ['SoundTwoTone', icons.SoundTwoTone],
    ['StarTwoTone', icons.StarTwoTone],
    ['SwitcherTwoTone', icons.SwitcherTwoTone],
    ['TabletTwoTone', icons.TabletTwoTone],
    ['TagTwoTone', icons.TagTwoTone],
    ['TagsTwoTone', icons.TagsTwoTone],
    ['ThunderboltTwoTone', icons.ThunderboltTwoTone],
    ['ToolTwoTone', icons.ToolTwoTone],
    ['TrademarkCircleTwoTone', icons.TrademarkCircleTwoTone],
    ['TrophyTwoTone', icons.TrophyTwoTone],
    ['UnlockTwoTone', icons.UnlockTwoTone],
    ['UsbTwoTone', icons.UsbTwoTone],
    ['VideoCameraTwoTone', icons.VideoCameraTwoTone],
    ['WalletTwoTone', icons.WalletTwoTone],
]);


export const outlinedAllIcons: ReadonlyMap<string, React.ComponentType<any>>[] = [outlinedDirectionIcons, outlinedSuggestionIcons, outlinedEditorIcons, outlinedDataIcons, outlinedLogoIcons, outlinedWebIcons];

export const filledAllIcons: ReadonlyMap<string, React.ComponentType<any>>[] = [filledDirectionIcons, filledSuggestionIcons, filledEditorIcons, filledDataIcons, filledLogoIcons, filledWebIcons];

export const twotoneAllIcons: ReadonlyMap<string, React.ComponentType<any>>[] = [twotoneDirectionIcons, twotoneSuggestionIcons, twotoneEditorIcons, twotoneDataIcons, twotoneLogoIcons, twotoneWebIcons];

export const directionAllIcons: ReadonlyMap<string, React.ComponentType<any>>[] = [outlinedDirectionIcons, filledDirectionIcons, twotoneDirectionIcons];

export const suggestionAllIcons: ReadonlyMap<string, React.ComponentType<any>>[] = [outlinedSuggestionIcons, filledSuggestionIcons, twotoneSuggestionIcons];

export const editorAllIcons: ReadonlyMap<string, React.ComponentType<any>>[] = [outlinedEditorIcons, filledEditorIcons, twotoneEditorIcons];

export const dataAllIcons: ReadonlyMap<string, React.ComponentType<any>>[] = [outlinedDataIcons, filledDataIcons, twotoneDataIcons];

export const logoAllIcons: ReadonlyMap<string, React.ComponentType<any>>[] = [outlinedLogoIcons, filledLogoIcons, twotoneLogoIcons];

export const webAllIcons: ReadonlyMap<string, React.ComponentType<any>>[] = [outlinedWebIcons, filledWebIcons, twotoneWebIcons];


export const allIconTypes: ReadonlyMultiKeyMap<string, ReadonlyMap<string, React.ComponentType<any>>> = ReadonlyMultiKeyMap.of([
    [['outlined', 'direction'], outlinedDirectionIcons],
    [['outlined', 'suggestion'], outlinedSuggestionIcons],
    [['outlined', 'editor'], outlinedEditorIcons],
    [['outlined', 'data'], outlinedDataIcons],
    [['outlined', 'logo'], outlinedLogoIcons],
    [['outlined', 'web'], outlinedWebIcons],
    [['filled', 'direction'], filledDirectionIcons],
    [['filled', 'suggestion'], filledSuggestionIcons],
    [['filled', 'editor'], filledEditorIcons],
    [['filled', 'data'], filledDataIcons],
    [['filled', 'logo'], filledLogoIcons],
    [['filled', 'web'], filledWebIcons],
    [['twotone', 'direction'], twotoneDirectionIcons],
    [['twotone', 'suggestion'], twotoneSuggestionIcons],
    [['twotone', 'editor'], twotoneEditorIcons],
    [['twotone', 'data'], twotoneDataIcons],
    [['twotone', 'logo'], twotoneLogoIcons],
    [['twotone', 'web'], twotoneWebIcons],
]);
